


name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  info:
    name: Info
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Action 1
        id: mod_id
        uses: dreamli0/my-action@main
        with:
          hi-there: ${{ secrets.AWS_SECRETS }}
          
      - name: Action 2
        id: action_2
        uses: ciplugins-poc/my-action@v1.0.2
        with:
          who-to-greet: 'action_2'
